/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type StepStatus = "awaiting_approval" | "denied" | "denied_expired" | "failed" | "pending" | "running" | "skipped" | "succeeded" | "timed_out";

export type StepType = "synthesis" | "tool_call" | "verification";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type ToolClassification = "read" | "write";

export type TurnStatus = "acting" | "answered" | "awaiting_approval" | "budget_exhausted" | "cancelled" | "failed" | "loop_detected" | "observing" | "planning" | "refused" | "synthesising" | "verifying";

export type VersionStatus = "chunking" | "embedding" | "failed" | "indexed" | "parsed" | "parsing" | "purged" | "quarantined" | "superseded" | "uploaded";

export interface AgentSteps {
  created_at: Generated<Timestamp>;
  ended_at: Timestamp | null;
  error_code: string | null;
  id: Generated<string>;
  latency_ms: number | null;
  rationale: string | null;
  result_ref: Json | null;
  result_summary: string | null;
  seq: number;
  started_at: Timestamp | null;
  status: Generated<StepStatus>;
  tool_id: string | null;
  tool_input: Json | null;
  tool_name: string | null;
  turn_id: string;
  type: StepType;
}

export interface AllowlistEntries {
  created_at: Generated<Timestamp>;
  created_by: string;
  enabled: Generated<boolean>;
  host: string;
  id: Generated<string>;
  port: Generated<number>;
  protocol: Generated<string>;
  purpose: string;
}

export interface Answers {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  is_refusal: Generated<boolean>;
  model_id: string | null;
  prompt_version: string | null;
  text: string;
  turn_id: string;
}

export interface ApprovalDecisions {
  approval_request_id: string;
  decided_at: Generated<Timestamp>;
  decided_by: string;
  decision: string;
  id: Generated<string>;
  reason: string | null;
}

export interface ApprovalRequests {
  agent_step_id: string;
  created_at: Generated<Timestamp>;
  decided_at: Timestamp | null;
  expires_at: Timestamp;
  id: Generated<string>;
  payload: Json;
  reason: string;
  requested_by: string;
  tool_id: string;
  turn_id: string;
}

export interface AuditEvents {
  action: string;
  actor_ip: string | null;
  actor_user_id: string | null;
  correlation_id: string;
  detail: Generated<Json>;
  hash: Buffer;
  id: Generated<Int8>;
  object_id: string | null;
  object_kind: string;
  occurred_at: Generated<Timestamp>;
  prev_hash: Buffer | null;
  workspace_id: string | null;
}

export interface Chunks {
  char_end: number;
  char_start: number;
  chunk_no: number;
  document_version_id: string;
  embedding: string | null;
  heading_path: string | null;
  id: Generated<string>;
  page_from: number;
  page_to: number;
  text: string;
  text_search: Generated<string | null>;
  token_count: number;
}

export interface Citations {
  char_end: number;
  char_start: number;
  claim_id: string;
  document_version_id: string;
  id: Generated<string>;
  page_no: number | null;
}

export interface Claims {
  answer_id: string;
  id: Generated<string>;
  seq: number;
  supporting_quote: string | null;
  text: string;
  verdict: Generated<string>;
}

export interface Conversations {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  title: string | null;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface DocumentGrants {
  document_id: string;
  granted_at: Generated<Timestamp>;
  granted_by: string;
  user_id: string;
}

export interface Documents {
  content_type: string;
  created_at: Generated<Timestamp>;
  created_by: string;
  current_version_id: string | null;
  id: Generated<string>;
  restricted: Generated<boolean>;
  source_filename: string;
  title: string;
  workspace_id: string;
}

export interface DocumentVersions {
  byte_size: Int8;
  chunker_version: string | null;
  document_id: string;
  id: Generated<string>;
  indexed_at: Timestamp | null;
  page_count: number | null;
  parser_version: string | null;
  sha256: string;
  status: Generated<VersionStatus>;
  status_reason: string | null;
  storage_key: string;
  uploaded_at: Generated<Timestamp>;
  uploaded_by: string;
  version_no: number;
}

export interface EgressRecords {
  approval_request_id: string | null;
  bytes_in: Generated<Int8>;
  bytes_out: Generated<Int8>;
  destination: string;
  id: Generated<string>;
  occurred_at: Generated<Timestamp>;
  user_id: string | null;
}

export interface GroupMappings {
  created_at: Generated<Timestamp>;
  group_name: string;
  id: Generated<string>;
  provider: Generated<string>;
  system_role: string;
}

export interface LoginAttempts {
  attempted_at: Generated<Timestamp>;
  email: string;
  id: Generated<Int8>;
  ip: string | null;
  succeeded: boolean;
  user_id: string | null;
}

export interface McpServers {
  created_at: Generated<Timestamp>;
  created_by: string;
  credential_enc: Buffer | null;
  endpoint: string;
  id: Generated<string>;
  last_seen_at: Timestamp | null;
  name: string;
  rate_limit_per_minute: number | null;
  status: Generated<string>;
  timeout_ms: Generated<number>;
  transport: string;
}

export interface ModelProviderSettings {
  acknowledged_at: Timestamp | null;
  acknowledged_by: string | null;
  acknowledgement_text: string | null;
  api_key_enc: Buffer | null;
  created_at: Generated<Timestamp>;
  enabled: Generated<boolean>;
  id: Generated<string>;
  model_id: string;
  provider: string;
}

export interface Pages {
  document_version_id: string;
  extraction_method: string;
  id: Generated<string>;
  page_no: number;
  text: string;
}

export interface PreAuthorisations {
  created_at: Generated<Timestamp>;
  created_by: string;
  id: Generated<string>;
  justification: string;
  revoked_at: Timestamp | null;
  tool_id: string;
}

export interface RefreshTokens {
  expires_at: Timestamp;
  family_id: string;
  id: Generated<string>;
  issued_at: Generated<Timestamp>;
  replaced_by: string | null;
  revoked_at: Timestamp | null;
  revoked_reason: string | null;
  token_hash: string;
  used_at: Timestamp | null;
  user_id: string;
}

export interface SchemaMigrations {
  applied_at: Generated<Timestamp>;
  checksum: string;
  filename: string;
}

export interface Tools {
  classification: Generated<ToolClassification>;
  description: string;
  discovered_at: Generated<Timestamp>;
  enabled: Generated<boolean>;
  id: Generated<string>;
  input_schema: Json;
  mcp_server_id: string | null;
  min_system_role: Generated<string>;
  name: string;
}

export interface Turns {
  budget_ms: Generated<number>;
  budget_steps: Generated<number>;
  conversation_id: string;
  ended_at: Timestamp | null;
  id: Generated<string>;
  model_id: string | null;
  prompt_version: string | null;
  question: string;
  started_at: Generated<Timestamp>;
  status: Generated<TurnStatus>;
  steps_used: Generated<number>;
  user_id: string;
  workspace_ids: string[];
}

export interface Users {
  auth_source: Generated<string>;
  created_at: Generated<Timestamp>;
  display_name: string;
  email: string;
  id: Generated<string>;
  locked_until: Timestamp | null;
  password_hash: string | null;
  status: Generated<string>;
  system_role: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface WorkspaceMembers {
  added_at: Generated<Timestamp>;
  added_by: string | null;
  user_id: string;
  workspace_id: string;
  workspace_role: string;
}

export interface Workspaces {
  created_at: Generated<Timestamp>;
  created_by: string;
  description: string | null;
  id: Generated<string>;
  language_hint: Generated<string>;
  model_provider_override: string | null;
  name: string;
  status: Generated<string>;
}

export interface WriteSnapshots {
  agent_step_id: string;
  before_state: Json;
  captured_at: Generated<Timestamp>;
  id: Generated<string>;
  reverted_at: Timestamp | null;
  reverted_by: string | null;
  target_id: string;
  target_kind: string;
  tool_id: string;
}

export interface DB {
  agent_steps: AgentSteps;
  allowlist_entries: AllowlistEntries;
  answers: Answers;
  approval_decisions: ApprovalDecisions;
  approval_requests: ApprovalRequests;
  audit_events: AuditEvents;
  chunks: Chunks;
  citations: Citations;
  claims: Claims;
  conversations: Conversations;
  document_grants: DocumentGrants;
  document_versions: DocumentVersions;
  documents: Documents;
  egress_records: EgressRecords;
  group_mappings: GroupMappings;
  login_attempts: LoginAttempts;
  mcp_servers: McpServers;
  model_provider_settings: ModelProviderSettings;
  pages: Pages;
  pre_authorisations: PreAuthorisations;
  refresh_tokens: RefreshTokens;
  schema_migrations: SchemaMigrations;
  tools: Tools;
  turns: Turns;
  users: Users;
  workspace_members: WorkspaceMembers;
  workspaces: Workspaces;
  write_snapshots: WriteSnapshots;
}
